### ISSUE TITLE
[功能增强&讨论]Z大可以为磁贴项目增加一个index.html模板吗？

### ISSUE THREAD

**Issue by DeSireFire** [Zfour/Butterfly-magnet#1]
如题，Z大可以为磁贴项目增加一个index.html模板吗？

类似像[gitcalendar](https://github.com/Zfour/Butterfly-gitcalendar)中的index那样，
通过html模板直观的看到效果。

# 为何会有这样的需求？
Butterfly 算是一个更新很勤快的主题。  
加上个人强迫症的原因和pug苦手。  
所以，不太想通过直接修改hexo/theme原生的主题文件，来达到美化的目的。

# 个人的解决方案
以[gitcalendar](https://github.com/Zfour/Butterfly-gitcalendar)为例，这是我菜逼博客[快乐咸鱼の RaXianch 窝](https://raxianch.moe/)

使用的是hexo5的注入器+iframe标签的方式，从而将gitcalendar打进博客页面中。
就美化效果来看，感觉还行。

> 优势

这样，只要Butterfly 主题没有颠覆性的大刀阔斧，普通的更新用这样方法都可以兼顾。

> 劣势

* 配置起来没有原来方便
* 似乎不能通过config来直接设置部分美化参数
* 需要自己写一下hexo注入器或者辅助函数

当然这些劣势主要的原因还是因为我对hexo还不够了解。
在使用注入器的时候似乎是能读取config参数的，但是读取以后，我不知道要如何传递。

是否存在一种方案：
hexo注入器读取config参数，单独渲染pug成为html，然后加进或覆盖到页面中。
（如果这样都行，连iframe都可以省了。）

如果Z大觉得不可行，
那是否可以为该磁贴做一个通过VUE实现的index.html模板？

感激不尽！orz

**Comment by Zfour** [comment]
我准备过段时间把时钟、gitcalendar、磁贴
去除vue依赖，只采用js注入特定id的div容器
这样只用添加一个div和js就能适配不同主题
参考&nbsp;https://github.com/Zfour/hexo-moments-js
主要最近在写朋友圈这个项目，暂时没精力维护老项目
咕咕咕


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Zfour/Butterfly-magnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 晚上6:03
收件人:&nbsp;"Zfour/Butterfly-magnet"<Butterfly-magnet@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Zfour/Butterfly-magnet] [功能增强&amp;讨论]Z大可以为磁贴项目增加一个index.html模板吗？ (#1)





 
如题，Z大可以为磁贴项目增加一个index.html模板吗？
 
类似像gitcalendar中的index那样，
 通过html模板直观的看到效果。
 
为何会有这样的需求？
 
Butterfly 算是一个更新很勤快的主题。
 加上个人强迫症的原因和pug苦手。
 所以，不太想通过直接修改hexo/theme原生的主题文件，来达到美化的目的。
 
个人的解决方案
 
以gitcalendar为例，这是我菜逼博客[快乐咸鱼の RaXianch 窝(https://blog.raxianch.moe/)
 
使用的是hexo5的注入器+iframe标签的方式，从而将gitcalendar打进博客页面中。
 就美化效果来看，感觉还行。
  
优势
  
这样，只要Butterfly 主题没有颠覆性的大刀阔斧，普通的更新用这样方法都可以兼顾。
  
劣势
   
配置起来没有原来方便
 
似乎不能通过config来直接设置部分美化参数
 
需要自己写一下hexo注入器或者辅助函数
  
当然这些劣势主要的原因还是因为我对hexo还不够了解。
 在使用注入器的时候似乎是能读取config参数的，但是读取以后，我不知道要如何传递。
 
是否存在一种方案：
 hexo注入器读取config参数，单独渲染pug成为html，然后加进或覆盖到页面中。
 （如果这样都行，连iframe都可以省了。）
 
如果Z大觉得不可行，
 那是否可以为该磁贴做一个通过VUE实现的index.html模板？
 
感激不尽！orz

**Comment by DeSireFire** [comment]
哇，要是能不用于依赖。使用原生JS就实现的话，我是举双手赞成的。

依赖虽然很方便，但是碰到奇怪的版本冲突问题，很蛋疼。

也是因为这个原因，所以我用iframe标签，随便它爱咋依赖，反正是独立页面不会冲突到主体。哈哈

```text
时钟、gitcalendar、磁贴
去除vue依赖，只采用js注入特定id的div容器
这样只用添加一个div和js就能适配不同主题
```

期待Z大之后的更新！
那我这段时间就先琢磨其他的东西好了。
在此感谢！orz
